inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  Exclude:
    - bin/generate-report

Style/MethodCallWithArgsParentheses:
  Enabled: false

Naming/FileName:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
